export const types = {
	SET_USER: 'SET_USER',
	SET_MODAL: 'SET_MODAL',
	SET_MODAL_RESULT: 'SET_MODAL_RESULT',
	SET_USERS_URLS: 'SET_USERS_URLS',
	SET_CURRENT_URL: 'SET_CURRENT_URL',
	SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
	SET_PAGES: 'SET_PAGES',
	ADD_CONTENT: 'ADD_CONTENT',
	SET_DIRS: 'SET_DIRS',
	SET_CURRENT_DIR: 'SET_CURRENT_DIR',
	CREATE_DIR: 'CREATE_DIR',
	CHANGE_PARENT_DIR: 'CHANGE_PARENT_DIR'
}